# Generated by Django 3.1.4 on 2021-04-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="parent",
            new_name="reply",
        ),
    ]
